stages:
 - build
 - test

test-api:
  
  stage: test

  image: python:3.7
  
  before-script: 
    - cd api 
    - python3 -m venv
    - source venv/bin/activate
    - pip install -r requirements.txt

  script:
    - cd api
    - source venv/bin/activate
    - python manage.py test

