version: '3.6'
volumes:
  node_modules:
services:
  db:
    image: postgres
    ports:
      - 5432:5432

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./env/api/env.local
    volumes:
      - ./api:/usr/src:cached
    working_dir: /usr/src
    ports:
      - 8000:8000
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: ../docker/client/local/Dockerfile
    working_dir: /usr/src
    volumes:
      - ./client:/usr/src:cached
      - node_modules:/usr/src/node_modules/
    command: yarn start
    ports:
      - 3000:3000

  proxy:
    image: nginx:1.14
    restart: always
    ports:
      - 80:80
    volumes:
       - ./assets:/usr/share/nginx/assets
       - ./docker/proxy/local/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - client
      - db
